### ISSUE TITLE
Include a version of the .csv file with a header row

### ISSUE THREAD

**Issue by rhanton** [tobilg/aws-edge-locations#1]
I'm trying to plug this data in to a log-parser, but need a header row to do so.

**Comment by tobilg** [comment]
Thanks for the feedback @rhanton, I'll include the header in the next release. Will keep you posted!

**Comment by tobilg** [comment]
This is fixed with https://github.com/tobilg/aws-edge-locations/commit/70ded18115786b90e87be4bc5de7a526628a3fe1 A new version `0.1.1` will also be released shortly @rhanton.
