### ISSUE TITLE
Missing IAH and QRO

### ISSUE THREAD

**Issue by cweseloh** [tobilg/aws-edge-locations#10]
IAH and QRO are missing from the list.

**Comment by tobilg** [comment]
Houston is mapped to HOU, not IAH currently. Not sure if this needs to be corrected. Regarding QRO, what I find is https://en.wikipedia.org/wiki/Quer%C3%A9taro_Intercontinental_Airport and there's no AWS edge location there afaik.

**Comment by cweseloh** [comment]
I see "IAH50-C2" in my CloudFront log files.

Regarding QRO: https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-cloudfront-launches-in-two-new-countries-mexico-and-new-zealand/

**Comment by tobilg** [comment]
Thanks for the fast feedback. I'll look into changing the Houston mapping. 

Regarding QRO, it's not present on the CloudFront location page where the data is sourced from: https://aws.amazon.com/cloudfront/features/?nc1=h_ls

**Comment by cweseloh** [comment]
Interesting on QRO.  I see "QRO50-C1" in my log files.  I think it's from a known user in Costa Rica.

**Comment by tobilg** [comment]
I think it should be on the official site, though it was announced in the blog post you mentioned. I'll have a look how I can manually add edge locations eventually. I'd strongly prefer just to pull it from the official source to be honest...

**Comment by tobilg** [comment]
@cweseloh A fix for IAH is deployed with version `0.3.5`. I'll look into QRO.

**Comment by tobilg** [comment]
I pinged AWS and the CloudFront team yesterday via Twitter, and they added it at least to the English version of the page where the info is taken from. Unfortunately, they introduced a small change in the HTML code, so that automatic parsing doesn't really work. Will need to have a deeper look to provide a potential workaround...

**Comment by tobilg** [comment]
This is fixed since a while. Closing.
