### ISSUE TITLE
Region vs Pricing Region

### ISSUE THREAD

**Issue by sheyd** [tobilg/aws-edge-locations#11]
First off, thank you for maintaining this list!

I'm using this as part of a data model to calculate [pricing](https://aws.amazon.com/cloudfront/pricing/) based on Region. Is part of the intent of this project to track those associations as well? Certain groupings of countries per pricing is different from region, e.g. Israel & Europe are grouped together. I'm manually changing the CSV to suit my needs, but curious if adding a `pricing_region` column to the CSV might be helpful.

Feel free to close this issue if this isn't relevant to this project, and thanks again for putting this together!

**Comment by tobilg** [comment]
@sheyd that's a nice idea! How do you map the pricing region, country to region based on the document you linked?

**Comment by tobilg** [comment]
I just released version `0.4.1` which includes the pricing region in both JSON and CSV files.
