### ISSUE TITLE
Missing WAW prefix

### ISSUE THREAD

**Issue by Lyrkan** [tobilg/aws-edge-locations#12]
Hi there,

Got some requests on `WAW50-C1` lately, and `WAW` seems to be missing from the list.

I'm guessing this is an edge located in Warsaw which is currently mapped to `WMI`...

**Comment by tobilg** [comment]
Thanks for the issue/report @Lyrkan, I'll have a look

**Comment by tobilg** [comment]
This is now solved with version `0.4.8`.
