### ISSUE TITLE
New AWS Edge Location in Lagos, Nigeria

### ISSUE THREAD

**Issue by CetinSert** [tobilg/aws-edge-locations#13]
Hello,

I am writing to inform you that Amazon Web Services (AWS) has announced a **new** edge location in **Lagos**, **Nigeria**. This location was launched on June 15, 2023, and it is expected to provide a 20% improvement in latency, on average, for data delivered in Nigeria​[1](https://aws.amazon.com/about-aws/whats-new/2023/06/aws-edge-location-nigeria/)​.

[**RTEdge.net**](//rtedge.net/#flat)
[![image](https://github.com/tobilg/aws-edge-locations/assets/27027/ea8d7b5c-8a38-43c0-9887-28bc4d7e24e6)](//rtedge.net/#flat)

Here is the JSON object for this new location, which adheres to the format used in the aws-edge-locations repository:

```json
{
  "code": "LOS",
  "city": "Lagos",
  "state": null,
  "country": "Nigeria",
  "countryCode": "NG",
  "count": 1,
  "latitude": 6.5773701668,
  "longitude": 3.321160078,
  "region": "Africa",
  "pricingRegion": "Africa"
}
```

The code for the new edge location is "**LOS**50-P1"​[2](https://www.feitsui.com/en/article/3)​, and the latitude and longitude of the Murtala Muhammed International Airport in Lagos are given above, matching [speed.cloudflare.com/locations](https://speed.cloudflare.com/locations)!

I kindly request that you consider adding this information to the aws-edge-locations repository.

Thank you for your attention to this matter.

Best regards,
Cetin Sert
Elefunc, Inc.

---

Here is how we were adding it on-the-fly before https://github.com/tobilg/aws-edge-locations/commit/98bf50643e5a57da8ed20e523cbc59d3b23d7c0d to [our multi-cloud network map](//rtedge.net).

![image](https://github.com/tobilg/aws-edge-locations/assets/27027/6a51fc49-9b54-4aa0-9fcc-ae29e1c8e942)

**Comment by tobilg** [comment]
Closed via https://github.com/tobilg/aws-edge-locations/commit/98bf50643e5a57da8ed20e523cbc59d3b23d7c0d New version `0.4.16` was just published.
