### ISSUE TITLE
feat: include `geoname_id` in `EdgeLocation` result

### ISSUE THREAD

**Issue by jlarmstrongiv** [tobilg/aws-edge-locations#15]
Other services, like maxmind, provide a `geoname_id` with their location results.  

It would be great to add `geoname_id` to easily link `aws-edge-locations` with other results.

Having the `geoname_id` built-in at compile time would be the best option.  It may be possible to include much richer metadata with the results too.

See also
- https://www.geonames.org/
- https://www.npmjs.com/search?q=geoname

**Comment by tobilg** [comment]
You can probably do this yourself already by using the given IATA code (field `code`) and joining this to the geonames data. As the data is pretty large, see https://download.geonames.org/export/dump/ and I don't see an immediate benefit with adding this to the process, I'm afaid I have to close this issue. I hope I could give you a hint about hot to achieve this on another path...

**Comment by jlarmstrongiv** [comment]
@tobilg that’s exactly the path I took!  However, getting the data, importing it to SQLite, joining the tables, and using recursive queries turned out to be more of a challenge than I thought it would be.  I’m still working on it
