### ISSUE TITLE
Missing edge locations, cannot generate new dataset 

### ISSUE THREAD

**Issue by Tombarr** [tobilg/aws-edge-locations#18]
I'm trying to generate a new dataset to include [Turkey](https://aws.amazon.com/about-aws/whats-new/2024/02/aws-new-edge-location-turkiye/) and [Egypt](https://aws.amazon.com/about-aws/whats-new/2024/05/new-edge-location-egypt/), but ran into the following issues:

Airport codes are no longer available in JSON format at `https://datahub.io/core/airport-codes/r/airport-codes.json`. It appears they're still available as a CSV, which the [website](https://datahub.io/core/airport-codes) converts on-the-fly to JSON.

The `getLocations` function no longer returns locations from the page https://aws.amazon.com/cloudfront/features/. Likely the HTML structure has changed.

Is there another source of these data to add to the list manually?

**Comment by tobilg** [comment]
AWS had changed their site structure, and the airports datasource was no longer available. This is both fixed now. Notice that the data format has changed.
