### ISSUE TITLE
`count` missing after refactoring

### ISSUE THREAD

**Issue by CetinSert** [tobilg/aws-edge-locations#19]
@tobilg –
I was using the `count`s on RTEdge.net
![image](https://github.com/user-attachments/assets/8f095388-7afe-4418-99d4-326935880a7a)
as an additional table row where it was showing
```
  1/102
 12/6XX ← cannot calculate this now!
```

Will `count` come back or are they removed for good? If removed, what was/is the difficulty in preserving them?

**Comment by tobilg** [comment]
No, it won't come back unfortunately, as AWS no longer published it on the source page https://aws.amazon.com/de/cloudfront/features/

**Comment by CetinSert** [comment]
Thank you for the prompt response!
