### ISSUE TITLE
Launch Dates?

### ISSUE THREAD

**Issue by geoffreywiseman** [tobilg/aws-edge-locations#8]
Hey -- would be great to have launch dates in this data as well. I was kinda curious if I could make a map visualization over time showing the points of presence as they appear, but I'd have to track down all that date data. ;)

**Comment by tobilg** [comment]
That's a nice idea, but afaik the data is not available publically. If you have a data source please let me know.

**Comment by geoffreywiseman** [comment]
The best source I could find was the announcements. It's not bad, but it's probably not detailed enough to work retroactively to identify each and every edge location. I wonder if there's another source. If I can find anything I'll let you know.

**Comment by tobilg** [comment]
As there seems to be no accessibly data source for the launch dates, I'm closing this issue for now. Please feel free to reopen it once there's a datasource which coould be used.
